spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8084/
          predicates:
            - Path= /costomers-service/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path= /products-service/**



